[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "liushengkai", email = "liushengkai@fengtaotech.cn" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "bcrypt>=5.0.0",
    "fastapi>=0.143.0",
    "greenlet>=3.5.6",
    "loguru>=0.7.3",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.15.1",
    "redis>=8.1.0",
    "sqlalchemy>=2.1.4",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
